# Generated by Django 4.0.8 on 2024-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('record_id', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('C', 'Creation'), ('U', 'Update'), ('D', 'Deletion')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
