# Generated by Django 4.0.8 on 2024-01-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='record_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
