# Generated by Django 4.0.8 on 2024-01-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_record_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='record_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
